AWSTemplateFormatVersion: "2010-09-09"

Description:
  This represents an EC2 instance to expose my application via Kind

Resources:

  KindKeyPair:
    Type: 'AWS::EC2::KeyPair'
    Properties:
      KeyName: KindKeyPairCluster
  
  KindEC2Instance: 
    Type: AWS::EC2::Instance
    Properties: 
      InstanceType: "t2.micro"
      ImageId: "ami-0453898e98046c639"
      KeyName: !Ref KindKeyPair
      NetworkInterfaces: 
      - AssociatePublicIpAddress: "true"
        DeviceIndex: "0"
        GroupSet:  
          - !GetAtt KindSecurityGroup.GroupId
      UserData:
        Fn::Base64:  !Sub |
          #!/bin/bash -xe
          yum update -y
          
          echo 'export PATH="/usr/local/bin:$PATH"' >> /etc/profile
          source /etc/profile

          /opt/aws/bin/cfn-init -v -s ${AWS::StackId} -r KindEC2Instance --region ${AWS::Region} -c ascending
          /opt/aws/bin/cfn-signal -e $? --stack ${AWS::StackId} --resource SampleWaitCondition --region ${AWS::Region}
    Metadata:
      Comment: Install Kind
      AWS::CloudFormation::Init:
        configSets:
          ascending:
            - "kubetools"
            - "docker"
            - "kindtools"
  #          - "config"
            - "cluster"
        kubetools:
          commands:
            install-kubetools:
              command:  |
                cd ./home/ec2-user
                curl -LO https://storage.googleapis.com/kubernetes-release/release/`curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt`/bin/linux/amd64/kubectl
                chmod +x ./kubectl
                sudo mv ./kubectl /usr/local/bin/kubectl
        docker:
          commands:
            install-docker:
              command:  yum install docker -y
            start-docker:
              command:  systemctl start docker
        kindtools:
          commands: 
            install-kindtools:
              command: |
                cd ./home/ec2-user
                curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.20.0/kind-linux-amd64
                chmod +x ./kind
                sudo mv ./kind /usr/local/bin/kind
        # config:
        #   files: 
        #     /home/ec2-user/multi-cluster.yaml: 
        #       content: |
        #         kind: Cluster
        #         apiVersion: kind.x-k8s.io/v1alpha4
        #         nodes:
        #         - role: control-plane
        #         - role: worker
        cluster:
          commands:
            create-kind-cluster:
              command: |
                cd ./home/ec2-user
                mkdir .kube
                kind create cluster --name luffy-cluster --kubeconfig .kube/config
      # colocar o arquvivo ./kube/config no /root/./kube/config  (precisa de permissão)

    DependsOn: KindSecurityGroup

  SampleWaitCondition:
    Type: AWS::CloudFormation::WaitCondition
    CreationPolicy:
      ResourceSignal:
        Timeout: PT10M
        Count: 1

  KindSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: SSH and HTTP
      SecurityGroupIngress:
        - CidrIp: 0.0.0.0/0
          FromPort: 22
          IpProtocol: tcp
          ToPort: 22
        - CidrIp: 0.0.0.0/0
          FromPort: 443
          IpProtocol: tcp
          ToPort: 443
        - CidrIp: 0.0.0.0/0
          FromPort: 80
          IpProtocol: tcp
          ToPort: 80