FROM golang:1.18 AS builder

WORKDIR /app

COPY . .

ENV GO111MODULE=on \
    CGO_ENABLED=0 \  
    GOOS=linux \
    GOARCH=amd64

RUN  go build -o  main .

FROM scratch

COPY --from=builder /app/main /main

EXPOSE 8080

ENTRYPOINT [ "/main" ]