commitish: main
name-template: 'v$NEXT_PATCH_VERSION'
tag-template: 'v$NEXT_PATCH_VERSION'
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
template: |
  ## Info
  This Draft was deployed to `development`.

  ## How to Promote?
  In order to promote this to  `staging`, edit the draft as a **"pre-release"**.

  ## Changelog:
  $CHANGES