#https://github.com/kubernetes-sigs/kustomize/blob/master/examples/helloWorld/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: arbitrary

commonLabels:
  app: hello

commonAnnotations:
  author: Isaias Da Silva
  
resources:
- deployment.yaml
- service.yaml
- configMap.yaml