version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "default-pipeline"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-2xveyzrdgndl"
s3_prefix = "default-pipeline"
region = "sa-east-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
