AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: CI/CD example

Resources:
  DefaultRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: "TrustPolicyAllowCodePipelineToAssume"
            Effect: "Allow"
            Principal:
              Service:
                - "codepipeline.amazonaws.com"
            Action:
              - "sts:AssumeRole"

  CodePipelinePolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: "Policy to CodePipeline"
      Path: /
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: 'Allow'
            Action:
              - 's3:*'
            Resource:
              - '*'
          - Effect: "Allow"
            Action:
              - "codestar-connections:UseConnection"
            Resource:
              - '*'
          - Effect: "Allow"
            Action:
              - "codebuild:BatchGetBuilds"
              - "codebuild:StartBuild"
              - "codebuild:BatchGetBuildBatches"
              - "codebuild:StartBuildBatch"
            Resource:
              - "*"
          - Effect: "Allow"
            Action:
              - "states:DescribeExecution"
              - "states:DescribeStateMachine"
              - "states:StartExecution"
            Resource:
              - "*"
          - Effect: "Allow"
            Action:
              - "iam:PassRole"
            Resource:
              - "*"
      Roles:
        - !Ref  DefaultRole

  DefaultPipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: default-pipeline
      ArtifactStore:
        Location: default-bucket-serverless-sonar-pipeline
        Type: S3
      RoleArn: !GetAtt DefaultRole.Arn
      Stages:
        -
          Name: Source
          Actions:
            -
              Name: "RetrieveSourceCode"
              Namespace: "SourceVariables"
              ActionTypeId:
                Owner: AWS
                Category: Source
                Provider: CodeStarSourceConnection
                Version: "1"
              Configuration:
                FullRepositoryId: idasilva/aws-serverless
                BranchName:  main
                ConnectionArn: !Sub 'arn:aws:codestar-connections:${AWS::Region}:${AWS::AccountId}:connection/1fa06bc3-c387-47ca-9a9a-476a40e455a6'
                DetectChanges: false
              OutputArtifacts:
                - Name: BuildArtifact
        -
          Name: SAST - Analisys
          Actions:
            - Name: "review"
              Namespace: "DeployDevVariables"
              ActionTypeId:
                Owner: AWS
                Category: Build
                Provider: CodeBuild
                Version: "1"
              Configuration:
                ProjectName:  default-review-stage
              InputArtifacts:
                - Name: BuildArtifact
              OutputArtifacts:
                - Name: TestedSourceCode
            - Name: "Approval"
              ActionTypeId:
                Owner: AWS
                Category: Approval
                Provider: Manual
                Version: "1"
              Configuration:
                CustomData: !Sub "Validação da qualidade do Software"

  DefaultBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: default-bucket-serverless-sonar-pipeline
      AccessControl: Private
      
Outputs:
  PipelineName:
    Description: Pipeline name
    Value: !Ref DefaultPipeline
    Export:
      Name: !Join [ ':', [ !Ref 'AWS::StackName', 'PipelineName']]