version: 0.2

phases:

  pre_build:
    on-failure: ABORT
    commands:
      - cd ./luffy/services

  build:
    on-failure: ABORT
    commands:
      - sonar-scanner -Dsonar.login=$SONAR_TOKEN -Dsonar.projectKey=$PROJECT -Dsonar.sources=. -Dsonar.host.url=$HOST
  


   
