version = 0.1
[default.deploy.parameters]
stack_name = "sonar-project"
resolve_s3 = true
s3_prefix = "sonar-project"
region = "sa-east-1"
capabilities = "CAPABILITY_NAMED_IAM"
image_repositories = []
