apiVersion: eks.amazonaws.com/v1
kind: NodeClass
metadata:
  name: engenharia
spec:
  role: AmazonEKSAutoNodeRole

  subnetSelectorTerms:
    - id: subnet-018f1b1ae473d0509
    - id: subnet-01f48848dee6d26f9
    - id: subnet-06d84fa608a9b2b9f

  securityGroupSelectorTerms:
    - id: sg-0befa24799c7e3261

  ephemeralStorage:
    size: "80Gi"
---
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: engenharia
spec:
  template:
    metadata:
      labels:
        engenharia-team: engenharia
    spec:
      nodeClassRef:
        group: eks.amazonaws.com
        kind: NodeClass
        name: engenharia
      requirements:
        - key: "eks.amazonaws.com/instance-category"
          operator: In
          values: ["t", "c", "m"]
        - key: karpenter.sh/capacity-type
          operator: In
          values:
            - spot
        - key: "kubernetes.io/arch"
          operator: In
          values:
          - arm64
          - arm64
  limits:
    cpu: 30
    memory: 1000Gi
  disruption:
    consolidationPolicy: WhenEmptyOrUnderutilized
    consolidateAfter: 1m