version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "gh-archive-poc"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-bkvmecosh2wv"
s3_prefix = "gh-archive-poc"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
