AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  ETL - PROCESS WORKFLOW

  SAM Template

Globals:
  Function:
    Timeout: 900
    Tracing: Active

Resources:

  DataProcessETLLogs:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/events/${AWS::StackName}-stm'

  DataProcessETLStateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      Type: STANDARD
      Name: data-proccess-etl-stm
      DefinitionUri: statemachine/data-proccess-etl.asl.json
      Role: !GetAtt DataProcessETLExecutionRole.Arn
      DefinitionSubstitutions:
        DataProcessELTFunctionName: !GetAtt DataProcessETLFunction.Arn
      Tracing:
        Enabled: true
      Logging:
        Destinations:
          - CloudWatchLogsLogGroup:
              LogGroupArn: !GetAtt DataProcessETLLogs.Arn
        IncludeExecutionData: true
        Level: 'ALL'
      Events:
        etlJob:
          Type: Schedule
          Properties:
            Name: data-process-etl-event-job
            Enabled: False
            Schedule: "rate(2 minutes)"
            Input:
              |-
                { "event": {
                     "date": "2023-01-01",
                     "hour": "1"
                     }
                }

  DataProcessETLFunction:
    Type: AWS::Serverless::Function 
    Properties:
      FunctionName:  data-proccess-etl-job
      CodeUri: ./lambda/data-proccess/hello_world/
      Handler: app.lambda_handler
      MemorySize: 10240
      Runtime: python3.9
      Architectures:
      - x86_64
      Tags:
        Todo: proccess-data
      Layers: 
        - arn:aws:lambda:us-east-1:336392948345:layer:AWSSDKPandas-Python39:4

  DataInsigthsETLFunction:
    Type: AWS::Serverless::Function 
    Properties:
      FunctionName:  data-insights-etl-job
      CodeUri:  ./lambda/data-insights/hello_world/
      Handler: app.lambda_handler
      MemorySize: 10240
      Runtime: python3.9
      Architectures:
      - x86_64
      Tags:
        Todo: insights-data
      
  DataPersistentETLFunction:
    Type: AWS::Serverless::Function 
    Properties:
      FunctionName: data-persistent-etl-job
      CodeUri: ./lambda/data-persistent/hello_world/
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Tags:
        Todo: persist-data
      Layers: 
        - arn:aws:lambda:us-east-1:336392948345:layer:AWSSDKPandas-Python39:4


  DataProcessETLExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${AWS::StackName}-${AWS::Region}-statemachine-role
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: states.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: AWSXRayDaemonWriteAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 'xray:PutTraceSegments'
                  - 'xray:PutTelemetryRecords'
                  - 'xray:GetSamplingRules'
                  - 'xray:GetSamplingTargets'
                  - 'xray:GetSamplingStatisticSummaries'
                Resource: '*'
        - PolicyName: AllowInvokeFuntions
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 'logs:*'
                  - 'cloudwatch:*'
                Resource:
                  - "*"
              - Effect: Allow
                Action: lambda:InvokeFunction
                Resource:
                  - !Sub 'arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:data-proccess-etl-job*'
                  - !Sub 'arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:data-persistent-etl-job*'
                  - !Sub 'arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:data-insights-etl-job*'

Outputs:
  DataProcessETLFunction:
    Description: DataProcessETLFunction ARN
    Value: !GetAtt DataProcessETLFunction.Arn