Transform: AWS::Serverless-2016-10-31

Description: >
  SAM Definitions

Environment:
  Type: String
  Description: Environment to deploy
  AllowedValues:
    - prod
    - pre-prod
    - dev


Globals:
  Function:
    Runtime: provided.al2
    Handler: bootstrap
    Timeout: 900
    Tracing: Active

Resources:
  ExemploFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: makefile
    Properties:
      FunctionName: !Sub exemplo-function-${Environment}
      CodeUri: ./
      Architectures:
        - arm64