version = 0.1
[default.deploy.parameters]
stack_name = "luffy-opensearch--projetct"
resolve_s3 = true
s3_prefix = "luffy-opensearch--projetct"
region = "sa-east-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
