name: "Lint PR"

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

permissions:
  pull-requests: read

jobs:
  main:
    name: Validate PR title
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        id: lint_pr_title
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          types: |
            [
          scopes: |
            ENG-\d+]
            IFS-\d+]
          headerPattern: ^(\W*)((ENG|IFS)-\d+\]) (.*)$
          requireScope: true
          headerPatternCorrespondence: type, scope, subject
          subjectPattern: ^.*$