name: STAGING

on:
  issue_comment:
    types: [created]

permissions:
  pull-requests: write
  deployments: write
  contents: write
  checks: read
  statuses: read

jobs:
  deploy:
    name: deploy
    if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-latest

    steps:
      - name: branch-deploy
        id: branch-deploy
        uses: github/branch-deploy@v9.1.3
        with:
          trigger: ".deploy"
          environment: "development"
          environment_targets: "production,development,staging"
          disable_naked_commands: "true"
          stable_branch: "main"

      - name: Checkout
        if: steps.branch-deploy.outputs.continue == 'true'
        uses: actions/checkout@v4
        with:
          ref: ${{ steps.branch-deploy.outputs.ref }}
          
      - name: deploy
        if: ${{ steps.branch-deploy.outputs.continue == 'true' && steps.branch-deploy.outputs.noop != 'true' }}
        run: |
          echo ${{ fromJson('{ "development": "CONTA A", "staging": "CONTA B" }')[${{ steps.branch-deploy.outputs.environment}}]}}
          ls -a
