name: branch-deploy


on:
  issue_comment:
    types: [created]

permissions:
  pull-requests: write
  deployments: write
  contents: write
  checks: read
  statuses: read

jobs:
  deploy:
    name: deploy
    if:  ${{ github.event.issue.pull_request &&
      (startsWith(github.event.comment.body, '.deploy staging') ||
      startsWith(github.event.comment.body, '.lock') ||
      startsWith(github.event.comment.body, '.help') ||
      startsWith(github.event.comment.body, '.unlock')) }}
    runs-on: ubuntu-latest

    steps:
      - name: branch-deploy
        id: branch-deploy
        uses: github/branch-deploy@v9.1.3
        with:
          trigger: ".deploy"
          environment: "staging"
          stable_branch: "main"

      - name: Checkout
        if: steps.branch-deploy.outputs.continue == 'true'
        uses: actions/checkout@v4
        with:
          ref: ${{ steps.branch-deploy.outputs.ref }}
          
      - name: deploy
        if: ${{ steps.branch-deploy.outputs.continue == 'true' && steps.branch-deploy.outputs.noop != 'true' }}
        run: |
          echo "DEPLOY ON STAGING"
          ls -a
