name: Developmente Deploy

on:
  push:
    branches: main

jobs: 
  build:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.merge_commit_sha }}
          fetch-depth: '0'

      - name: DEPLOY
        id: novo
        run: |
         echo "DEPLOY DEVELOPMENT"

      - name: Bump version and push tag
        id: semantic
        uses: anothrNick/github-tag-action@v1 # Don't use @master or @v1 unless you're happy to test the latest version
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }} # if you don't want to set write permissions use a PAT token
          WITH_V: true
          DEFAULT_BUMP: false
          PRERELEASE: true
          PRERELEASE_SUFFIX: rc
          RELEASE_BRANCHES: release.*

      - uses: release-drafter/release-drafter@v6
        # (Optional) specify config name to use, relative to .github/. Default: release-drafter.yml
        with:
          prerelease: true
          tag: ${{ steps.semantic.outputs.new_tag }}
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}

      - name: Purge cache
        uses: jakejarvis/cloudflare-purge-action@master
        env:
          # Zone is required by both authentication methods
          CLOUDFLARE_ZONE: ${{ secrets.CLOUDFLARE_ZONE }}

          CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}

      # - name: Bump version and push tag
      #   id: semantic
      #   uses: mathieudutour/github-tag-action@v6.1
      #   with:
      #     github_token: ${{ secrets.TOKEN }}
      #     release_branches: .*

      # - name: Create Release
      #   uses: softprops/action-gh-release@v2
      #   with:
      #     token: ${{ secrets.TOKEN }}
      #     tag_name: ${{ steps.semantic.outputs.new_tag }}
      #     draft: true
      #     prerelease: false
      #     make_latest: false
      #     generate_release_notes: true
      #     body: |
      #       ## Info
      #       Commitr ${{ github.sha }} was deployed to `development`. [See code diff](${{ github.event.compare }}).

      #       It was initialized by [${{ github.event.sender.login }}](${{ github.event.sender.html_url }}).

      #       ## How to Promote?
      #       In order to promote this to staging, edit the draft and press **"Publish pre-release"**.