name: Developmente Deploy

on:
  push:
    branches: semantic-version

jobs: 
  build:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: DEPLOY
        id: novo
        run: |
         echo "DEPLOY DEVELOPMENT"

      - name: Bump version and push tag
        id: semantic
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.TOKEN }}
          append_to_pre_release_tag: "rc"

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.TOKEN }}
          tag_name: ${{ steps.semantic.outputs.new_tag }}
          draft: true
          prerelease: true
          generate_release_notes: true