name: First Workflow

on:
  push:
    branches: [ ec2-instace-connect ]

env:
  AWS_REGION: "us-east-1"
  AWS_ROLE: "arn:aws:iam::560978416398:role/GitHubAction-AssumeRoleWithAction."

jobs: 
  build:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ env.AWS_ROLE }}
          aws-region: ${{ env.AWS_REGION }}
    
      - name: Ssh proxy command
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          ssh-keyscan -H "172.31.111.208" >> ~/.ssh/known_hosts
          ./deploy.sh