name: New Hotfix tag was published

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+.*-hotfix"

jobs: 
  build:
    runs-on: ubuntu-latest
    
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 10

      - name: Build
        run: |
          ls -a
          echo "tag ${{ github.ref_name }}"
