name: Production Deployment

on:
  release:
    types: [released]

jobs: 
  build:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: DEPLOY
        id: novo
        run: |
          echo "DEPLOY PRODUCTION"