name: Production Deployment

on:
  release:
    types: [released]

jobs: 
  build:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      # - uses: actions/checkout@v4
      #   with:
      #     ref: ${{ github.event.pull_request.merge_commit_sha }}
      #     fetch-depth: '0'

      # - name: Bump version and push tag
      #   id: semantic
      #   uses: anothrNick/github-tag-action@v1 # Don't use @master or @v1 unless you're happy to test the latest version
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.TOKEN }} # if you don't want to set write permissions use a PAT token
      #     WITH_V: true
      #     DEFAULT_BUMP: false
      #     PRERELEASE: true
      #     PRERELEASE_SUFFIX: rc
      #     RELEASE_BRANCHES: release.*

      # - uses: release-drafter/release-drafter@v6
      #   # (Optional) specify config name to use, relative to .github/. Default: release-drafter.yml
      #   with:
      #     prerelease: true
      #     tag: ${{ steps.semantic.outputs.new_tag }}
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.TOKEN }}

      # - uses: actions/checkout@v4
      #   with:
      #     path: '.'

      # # You can make whatever type of change to the repo...
      # - run: echo "${{ github.ref_name }}" > ./VERSION

      # # ...and then use the action as you would normally do, but providing the path to the repo
      # - uses: EndBug/add-and-commit@v9
      #   with:
      #     message: 'Bump version...'
      #     add: 'VERSION --force'
      #     cwd: './'

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.TOKEN }}
          ref: main

      - run: echo "${{ github.ref_name }}" > ./VERSION

      # - uses: EndBug/add-and-commit@v9
      #   with:
      #     message: Bump version...
      

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.TOKEN }}
          title: "[ENG-000] Bump version"

      - name: Enable Pull Request Automerge
        if: steps.cpr.outputs.pull-request-operation == 'created'
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.TOKEN }}
          pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}
          merge-method: merge

      - name: DEPLOY
        id: novo
        run: |
          echo "DEPLOY PRODUCTION"