name: Continuos Integration

on:
  push:
    branches:
      - main
      - sonarcloud
  pull_request:
      types: [opened, synchronize, reopened]

jobs:
  sonarqube:
    runs-on: ubuntu-latest
    working-directory: ./nextjs-app
    environment: Development

    steps:

    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: actions/setup-node@v2
      with:
        node-version: "16"
        cache: "yarn"

    - run: npm install
    
    - run: npm test:coverage

    - name: SonarQube Scan
      uses: sonarsource/sonarqube-scan-action@master
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
    
    - name: SonarQube Quality Gate check
      id: sonarqube-quality-gate-check
      uses: sonarsource/sonarqube-quality-gate-action@master
      timeout-minutes: 5
      env:
       SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
       SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

    - name: "SonarQube Quality Gate Status"
      run: echo "The Quality Gate status is ${{ steps.sonarqube-quality-gate-check.outputs.quality-gate-status }}"
